/**
 * lib/models.ts
 * ─────────────────────────────────────────────────────────────
 * SINGLE SOURCE OF TRUTH for all model data across DefiledAI.
 *
 * To add a new model: add one entry to MODELS below.
 * Every tool (compatibility checker, can-i-run-it, speed estimator,
 * uncensored database, HF tracker) imports from here automatically.
 * ─────────────────────────────────────────────────────────────
 */

export type ModelType = "abliterated" | "uncensored" | "dolphin";
export type ModelDomain = "general" | "coding" | "reasoning" | "writing" | "math" | "multilingual" | "medical";

export interface Model {
  id: string;
  name: string;
  family: string;
  org: string;
  params: number;          // billions
  type: ModelType;
  domain: ModelDomain;
  method: string;          // "Abliteration" | "Fine-tune (Dolphin)" | etc
  author: string;          // HF username of abliterator
  vramQ4: number;          // GB at Q4_K_M
  toks4090: number;        // tok/s on RTX 4090 (0 = doesn't fit)
  quants: string[];
  hf: string;              // HuggingFace URL
  qualityRetention: number; // 0–100
  rating: number;          // community rating 0–5
  votes: number;
  note: string;
  tags: string[];
  addedDate: string;       // ISO date — used for What's New
  isNew?: boolean;         // auto-computed, set true if < 14 days old
}

export const MODELS: Model[] = [
  // ── Dolphin series ───────────────────────────────────────────
  {
    id: "dolphin-3-llama32-3b",
    name: "Dolphin 3.0 Llama 3.2 3B",
    family: "Dolphin",
    org: "CognitiveComputations",
    params: 3,
    type: "dolphin",
    domain: "general",
    method: "Fine-tune (Dolphin)",
    author: "cognitivecomputations",
    vramQ4: 2.2,
    toks4090: 245,
    quants: ["Q4_K_M", "Q5_K_M", "Q8_0"],
    hf: "https://huggingface.co/cognitivecomputations/dolphin-3.0-llama3.2-3b",
    qualityRetention: 97,
    rating: 4.6,
    votes: 89,
    note: "Newest Dolphin on Llama 3.2 3B. Runs on 4GB VRAM. Very fast.",
    tags: ["dolphin", "tiny", "fast", "beginner"],
    addedDate: "2026-05-28",
  },
  {
    id: "dolphin-29-llama31-8b",
    name: "Dolphin 2.9 Llama 3.1 8B",
    family: "Dolphin",
    org: "CognitiveComputations",
    params: 8,
    type: "dolphin",
    domain: "general",
    method: "Fine-tune (Dolphin)",
    author: "cognitivecomputations",
    vramQ4: 5.5,
    toks4090: 128,
    quants: ["Q4_K_M", "Q5_K_M", "Q8_0"],
    hf: "https://huggingface.co/cognitivecomputations/dolphin-2.9-llama3-8b",
    qualityRetention: 98,
    rating: 4.8,
    votes: 334,
    note: "Most popular uncensored 8B. Best entry-level Dolphin model.",
    tags: ["dolphin", "chat", "fast", "beginner"],
    addedDate: "2026-04-01",
  },
  {
    id: "dolphin-29-llama31-70b",
    name: "Dolphin 2.9 Llama 3.1 70B",
    family: "Dolphin",
    org: "CognitiveComputations",
    params: 70,
    type: "dolphin",
    domain: "general",
    method: "Fine-tune (Dolphin)",
    author: "cognitivecomputations",
    vramQ4: 40.2,
    toks4090: 0,
    quants: ["Q4_K_M", "Q5_K_M"],
    hf: "https://huggingface.co/cognitivecomputations/dolphin-2.9-llama3-70b",
    qualityRetention: 97,
    rating: 4.7,
    votes: 198,
    note: "Best quality Dolphin. Needs 48GB VRAM (dual 3090 NVLink).",
    tags: ["dolphin", "70b", "chat", "creative"],
    addedDate: "2026-04-01",
  },
  {
    id: "dolphin-28-mistral-7b",
    name: "Dolphin 2.8 Mistral 7B",
    family: "Dolphin",
    org: "CognitiveComputations",
    params: 7,
    type: "dolphin",
    domain: "general",
    method: "Fine-tune (Dolphin)",
    author: "cognitivecomputations",
    vramQ4: 4.8,
    toks4090: 141,
    quants: ["Q4_K_M", "Q5_K_M", "Q8_0"],
    hf: "https://huggingface.co/cognitivecomputations/dolphin-2.8-mistral-7b-v02",
    qualityRetention: 98,
    rating: 4.7,
    votes: 287,
    note: "Classic Dolphin on Mistral. Fast, reliable, widely tested.",
    tags: ["dolphin", "chat", "fast"],
    addedDate: "2026-03-01",
  },
  {
    id: "dolphin-29-mixtral-8x22b",
    name: "Dolphin 2.9 Mixtral 8x22B",
    family: "Dolphin",
    org: "CognitiveComputations",
    params: 141,
    type: "dolphin",
    domain: "general",
    method: "Fine-tune (Dolphin)",
    author: "cognitivecomputations",
    vramQ4: 43.0,
    toks4090: 0,
    quants: ["Q2_K", "Q4_K_M"],
    hf: "https://huggingface.co/cognitivecomputations/dolphin-2.9-mixtral-8x22b",
    qualityRetention: 96,
    rating: 4.5,
    votes: 112,
    note: "Dolphin on MoE. Exceptional quality when hardware allows.",
    tags: ["dolphin", "moe", "creative"],
    addedDate: "2026-03-01",
  },
  {
    id: "dolphin-26-phi2",
    name: "Dolphin 2.6 Phi-2 2.7B",
    family: "Dolphin",
    org: "CognitiveComputations",
    params: 2.7,
    type: "dolphin",
    domain: "general",
    method: "Fine-tune (Dolphin)",
    author: "cognitivecomputations",
    vramQ4: 2.1,
    toks4090: 210,
    quants: ["Q4_K_M", "Q8_0"],
    hf: "https://huggingface.co/cognitivecomputations/dolphin-2_6-phi-2",
    qualityRetention: 95,
    rating: 4.3,
    votes: 156,
    note: "Runs on 4GB VRAM. Fastest uncensored model available.",
    tags: ["dolphin", "tiny", "fast", "4gb"],
    addedDate: "2026-02-01",
  },

  // ── Llama Abliterated ─────────────────────────────────────────
  {
    id: "llama32-1b-ablit",
    name: "Llama 3.2 1B Abliterated",
    family: "Llama Abliterated",
    org: "Meta / bartowski",
    params: 1,
    type: "abliterated",
    domain: "general",
    method: "Abliteration",
    author: "bartowski",
    vramQ4: 0.8,
    toks4090: 480,
    quants: ["Q4_K_M", "Q8_0", "F16"],
    hf: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-abliterated",
    qualityRetention: 99,
    rating: 4.2,
    votes: 67,
    note: "Smallest usable abliterated model. 1GB VRAM. Extremely fast.",
    tags: ["abliterated", "tiny", "fast", "1b", "beginner"],
    addedDate: "2026-05-20",
  },
  {
    id: "llama32-3b-ablit",
    name: "Llama 3.2 3B Abliterated",
    family: "Llama Abliterated",
    org: "Meta / bartowski",
    params: 3,
    type: "abliterated",
    domain: "general",
    method: "Abliteration",
    author: "bartowski",
    vramQ4: 2.2,
    toks4090: 245,
    quants: ["Q4_K_M", "Q5_K_M", "Q8_0"],
    hf: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-abliterated",
    qualityRetention: 99,
    rating: 4.5,
    votes: 134,
    note: "Best tiny abliterated model. Runs on 4GB VRAM at very high speed.",
    tags: ["abliterated", "tiny", "fast", "beginner"],
    addedDate: "2026-05-15",
  },
  {
    id: "llama31-8b-ablit",
    name: "Llama 3.1 8B Abliterated",
    family: "Llama Abliterated",
    org: "Meta / FailSpy",
    params: 8,
    type: "abliterated",
    domain: "general",
    method: "Abliteration",
    author: "failspy",
    vramQ4: 5.5,
    toks4090: 126,
    quants: ["Q4_K_M", "Q5_K_M", "Q8_0", "F16"],
    hf: "https://huggingface.co/failspy/Llama-3-8B-Instruct-abliterated",
    qualityRetention: 99,
    rating: 4.8,
    votes: 312,
    note: "FailSpy abliteration. 99.2% MMLU retention. Community favourite.",
    tags: ["abliterated", "chat", "fast", "beginner"],
    addedDate: "2026-03-01",
  },
  {
    id: "llama31-70b-ablit",
    name: "Llama 3.1 70B Abliterated",
    family: "Llama Abliterated",
    org: "Meta / FailSpy",
    params: 70,
    type: "abliterated",
    domain: "general",
    method: "Abliteration",
    author: "failspy",
    vramQ4: 40.2,
    toks4090: 0,
    quants: ["Q2_K", "Q4_K_M", "Q5_K_M", "IQ3_M"],
    hf: "https://huggingface.co/failspy/Meta-Llama-3-70B-Instruct-abliterated-v3",
    qualityRetention: 98,
    rating: 4.9,
    votes: 412,
    note: "Best overall abliterated model. v3 improves reasoning retention.",
    tags: ["abliterated", "70b", "chat", "coding", "reasoning"],
    addedDate: "2026-05-28",
  },

  // ── Mistral Abliterated ───────────────────────────────────────
  {
    id: "mistral-7b-ablit",
    name: "Mistral 7B v0.3 Abliterated",
    family: "Mistral Abliterated",
    org: "Mistral / FailSpy",
    params: 7,
    type: "abliterated",
    domain: "general",
    method: "Abliteration",
    author: "failspy",
    vramQ4: 4.8,
    toks4090: 138,
    quants: ["Q4_K_M", "Q5_K_M", "Q8_0", "F16"],
    hf: "https://huggingface.co/failspy/Mistral-7B-Instruct-v0.3-abliterated",
    qualityRetention: 99,
    rating: 4.8,
    votes: 287,
    note: "Cleanest abliteration at 7B. 99.2% MMLU retention.",
    tags: ["abliterated", "chat", "fast", "api"],
    addedDate: "2026-03-01",
  },
  {
    id: "mistral-nemo-ablit",
    name: "Mistral Nemo 12B Abliterated",
    family: "Mistral Abliterated",
    org: "Mistral / bartowski",
    params: 12,
    type: "abliterated",
    domain: "general",
    method: "Abliteration",
    author: "bartowski",
    vramQ4: 8.1,
    toks4090: 86,
    quants: ["Q4_K_M", "Q5_K_M", "Q6_K"],
    hf: "https://huggingface.co/bartowski/Mistral-Nemo-Instruct-2407-abliterated",
    qualityRetention: 98,
    rating: 4.5,
    votes: 134,
    note: "128K context retained. Strong mid-range abliterated option.",
    tags: ["abliterated", "128k", "context", "chat"],
    addedDate: "2026-04-01",
  },
  {
    id: "mistral-small-31-ablit",
    name: "Mistral Small 3.1 Abliterated",
    family: "Mistral Abliterated",
    org: "Mistral / Community",
    params: 24,
    type: "abliterated",
    domain: "general",
    method: "Abliteration",
    author: "community",
    vramQ4: 16.0,
    toks4090: 44,
    quants: ["Q4_K_M", "Q5_K_M"],
    hf: "https://huggingface.co/models?search=mistral+small+3.1+abliterated",
    qualityRetention: 97,
    rating: 4.4,
    votes: 78,
    note: "Mistral's newest small model with abliteration. 128K context.",
    tags: ["abliterated", "24b", "128k", "chat"],
    addedDate: "2026-05-22",
  },

  // ── Qwen Uncensored ───────────────────────────────────────────
  {
    id: "qwen3-4b-ablit",
    name: "Qwen 3 4B Abliterated",
    family: "Qwen Uncensored",
    org: "Alibaba / Community",
    params: 4,
    type: "abliterated",
    domain: "coding",
    method: "Abliteration",
    author: "community",
    vramQ4: 3.0,
    toks4090: 188,
    quants: ["Q4_K_M", "Q5_K_M", "Q8_0"],
    hf: "https://huggingface.co/models?search=qwen3+4b+abliterated",
    qualityRetention: 98,
    rating: 4.5,
    votes: 92,
    note: "Qwen 3 4B with refusal removed. Strong coding at tiny size.",
    tags: ["abliterated", "qwen3", "coding", "fast"],
    addedDate: "2026-05-25",
  },
  {
    id: "qwen3-8b-ablit",
    name: "Qwen 3 8B Abliterated",
    family: "Qwen Uncensored",
    org: "Alibaba / Community",
    params: 8,
    type: "abliterated",
    domain: "coding",
    method: "Abliteration",
    author: "community",
    vramQ4: 5.5,
    toks4090: 122,
    quants: ["Q4_K_M", "Q5_K_M", "Q8_0"],
    hf: "https://huggingface.co/models?search=qwen3+8b+abliterated",
    qualityRetention: 98,
    rating: 4.6,
    votes: 108,
    note: "Qwen 3 8B abliterated. Thinking mode available.",
    tags: ["abliterated", "qwen3", "coding", "reasoning"],
    addedDate: "2026-05-25",
  },
  {
    id: "qwen3-14b-ablit",
    name: "Qwen 3 14B Abliterated",
    family: "Qwen Uncensored",
    org: "Alibaba / Community",
    params: 14,
    type: "abliterated",
    domain: "coding",
    method: "Abliteration",
    author: "community",
    vramQ4: 9.5,
    toks4090: 68,
    quants: ["Q4_K_M", "Q5_K_M"],
    hf: "https://huggingface.co/models?search=qwen3+14b+abliterated",
    qualityRetention: 97,
    rating: 4.6,
    votes: 87,
    note: "Best mid-range Qwen 3 abliteration. Fits single 12GB GPU.",
    tags: ["abliterated", "qwen3", "coding", "12gb"],
    addedDate: "2026-05-25",
  },
  {
    id: "qwen3-32b-ablit",
    name: "Qwen 3 32B Abliterated",
    family: "Qwen Uncensored",
    org: "Alibaba / Community",
    params: 32,
    type: "abliterated",
    domain: "coding",
    method: "Abliteration",
    author: "community",
    vramQ4: 21.0,
    toks4090: 34,
    quants: ["Q4_K_M", "Q5_K_M"],
    hf: "https://huggingface.co/models?search=qwen3+32b+abliterated",
    qualityRetention: 97,
    rating: 4.7,
    votes: 115,
    note: "Top coding model that fits 24GB single GPU. Q4 = 21GB.",
    tags: ["abliterated", "qwen3", "coding", "24gb"],
    addedDate: "2026-05-25",
  },
  {
    id: "qwen25-72b-uncensored",
    name: "Qwen 2.5 72B Uncensored",
    family: "Qwen Uncensored",
    org: "Alibaba / Community",
    params: 72,
    type: "abliterated",
    domain: "coding",
    method: "Abliteration",
    author: "community",
    vramQ4: 41.0,
    toks4090: 0,
    quants: ["Q4_K_M", "Q5_K_M"],
    hf: "https://huggingface.co/models?search=qwen2.5+72b+uncensored",
    qualityRetention: 98,
    rating: 4.7,
    votes: 198,
    note: "Best uncensored coding model at 72B scale.",
    tags: ["abliterated", "coding", "72b", "multilingual"],
    addedDate: "2026-04-01",
  },

  // ── DeepSeek Abliterated ──────────────────────────────────────
  {
    id: "deepseek-r1-7b-ablit",
    name: "DeepSeek R1 7B Abliterated",
    family: "DeepSeek Abliterated",
    org: "DeepSeek / Community",
    params: 7,
    type: "abliterated",
    domain: "reasoning",
    method: "Abliteration",
    author: "community",
    vramQ4: 5.0,
    toks4090: 129,
    quants: ["Q4_K_M", "Q8_0"],
    hf: "https://huggingface.co/models?search=deepseek+r1+7b+abliterated",
    qualityRetention: 97,
    rating: 4.6,
    votes: 167,
    note: "Uncensored reasoning at 7B. Chain-of-thought fully intact.",
    tags: ["abliterated", "reasoning", "math", "7b"],
    addedDate: "2026-04-10",
  },
  {
    id: "deepseek-r1-70b-ablit",
    name: "DeepSeek R1 70B Abliterated",
    family: "DeepSeek Abliterated",
    org: "DeepSeek / Community",
    params: 70,
    type: "abliterated",
    domain: "reasoning",
    method: "Abliteration",
    author: "community",
    vramQ4: 40.0,
    toks4090: 0,
    quants: ["Q4_K_M", "Q5_K_M"],
    hf: "https://huggingface.co/models?search=deepseek+r1+70b+abliterated",
    qualityRetention: 97,
    rating: 4.8,
    votes: 241,
    note: "Best uncensored reasoning model locally. Needs 48GB VRAM.",
    tags: ["abliterated", "reasoning", "math", "70b"],
    addedDate: "2026-04-01",
  },

  // ── Gemma Abliterated ─────────────────────────────────────────
  {
    id: "gemma3-4b-ablit",
    name: "Gemma 3 4B Abliterated",
    family: "Gemma Abliterated",
    org: "Google / Community",
    params: 4,
    type: "abliterated",
    domain: "reasoning",
    method: "Abliteration",
    author: "community",
    vramQ4: 3.0,
    toks4090: 188,
    quants: ["Q4_K_M", "Q5_K_M", "Q8_0"],
    hf: "https://huggingface.co/models?search=gemma+3+4b+abliterated",
    qualityRetention: 97,
    rating: 4.4,
    votes: 78,
    note: "Google's newest Gemma 3 abliterated. 4GB VRAM.",
    tags: ["abliterated", "gemma3", "tiny", "fast"],
    addedDate: "2026-05-20",
  },
  {
    id: "gemma3-12b-ablit",
    name: "Gemma 3 12B Abliterated",
    family: "Gemma Abliterated",
    org: "Google / Community",
    params: 12,
    type: "abliterated",
    domain: "reasoning",
    method: "Abliteration",
    author: "community",
    vramQ4: 8.1,
    toks4090: 86,
    quants: ["Q4_K_M", "Q5_K_M", "Q8_0"],
    hf: "https://huggingface.co/models?search=gemma+3+12b+abliterated",
    qualityRetention: 97,
    rating: 4.5,
    votes: 91,
    note: "Gemma 3 12B abliterated. Strong reasoning for size.",
    tags: ["abliterated", "gemma3", "reasoning"],
    addedDate: "2026-05-20",
  },
  {
    id: "gemma2-27b-ablit",
    name: "Gemma 2 27B Abliterated",
    family: "Gemma Abliterated",
    org: "Google / Community",
    params: 27,
    type: "abliterated",
    domain: "reasoning",
    method: "Abliteration",
    author: "community",
    vramQ4: 18.0,
    toks4090: 44,
    quants: ["Q4_K_M", "Q5_K_M", "Q6_K"],
    hf: "https://huggingface.co/models?search=gemma+2+27b+abliterated",
    qualityRetention: 97,
    rating: 4.4,
    votes: 112,
    note: "Best single 24GB card abliterated model at 27B.",
    tags: ["abliterated", "27b", "reasoning"],
    addedDate: "2026-03-01",
  },

  // ── WizardLM ──────────────────────────────────────────────────
  {
    id: "wizardlm2-7b",
    name: "WizardLM-2 7B",
    family: "WizardLM",
    org: "Microsoft",
    params: 7,
    type: "uncensored",
    domain: "general",
    method: "Fine-tune",
    author: "microsoft",
    vramQ4: 4.8,
    toks4090: 139,
    quants: ["Q4_K_M", "Q5_K_M", "Q8_0"],
    hf: "https://huggingface.co/Microsoft/WizardLM-2-7B",
    qualityRetention: 97,
    rating: 4.4,
    votes: 134,
    note: "Microsoft's uncensored instruction model. Strong structured tasks.",
    tags: ["uncensored", "chat", "instruction"],
    addedDate: "2026-03-01",
  },
  {
    id: "wizardlm2-8x22b",
    name: "WizardLM-2 8x22B",
    family: "WizardLM",
    org: "Microsoft",
    params: 141,
    type: "uncensored",
    domain: "general",
    method: "Fine-tune",
    author: "microsoft",
    vramQ4: 43.0,
    toks4090: 0,
    quants: ["Q2_K", "Q4_K_M"],
    hf: "https://huggingface.co/Microsoft/WizardLM-2-8x22B",
    qualityRetention: 96,
    rating: 4.5,
    votes: 98,
    note: "MoE architecture. Exceptional capability when hardware allows.",
    tags: ["uncensored", "moe", "large"],
    addedDate: "2026-03-01",
  },

  // ── Phi Uncensored ────────────────────────────────────────────
  {
    id: "phi4-uncensored",
    name: "Phi-4 Uncensored",
    family: "Phi Uncensored",
    org: "Microsoft / Community",
    params: 14,
    type: "uncensored",
    domain: "coding",
    method: "Fine-tune",
    author: "community",
    vramQ4: 9.5,
    toks4090: 68,
    quants: ["Q4_K_M", "Q5_K_M", "Q8_0"],
    hf: "https://huggingface.co/models?search=phi+4+uncensored",
    qualityRetention: 96,
    rating: 4.3,
    votes: 67,
    note: "Microsoft Phi-4 fine-tuned for unrestricted use. Strong coder.",
    tags: ["uncensored", "coding", "phi4"],
    addedDate: "2026-05-18",
  },
  {
    id: "phi3-medium-uncensored",
    name: "Phi-3 Medium Uncensored",
    family: "Phi Uncensored",
    org: "Microsoft / Community",
    params: 14,
    type: "uncensored",
    domain: "coding",
    method: "Fine-tune",
    author: "community",
    vramQ4: 9.5,
    toks4090: 68,
    quants: ["Q4_K_M", "Q5_K_M", "Q8_0"],
    hf: "https://huggingface.co/models?search=phi+3+medium+uncensored",
    qualityRetention: 96,
    rating: 4.3,
    votes: 89,
    note: "128K context window retained. Good for long documents.",
    tags: ["uncensored", "coding", "128k"],
    addedDate: "2026-03-01",
  },
];

// ── Helpers ────────────────────────────────────────────────────

const TWO_WEEKS_MS = 14 * 24 * 60 * 60 * 1000;

/** Returns all models, with isNew computed from addedDate */
export function getAllModels(): Model[] {
  const now = Date.now();
  return MODELS.map(m => ({
    ...m,
    isNew: now - new Date(m.addedDate).getTime() < TWO_WEEKS_MS,
  }));
}

/** Models added in the last N days */
export function getRecentModels(days = 14): Model[] {
  const cutoff = Date.now() - days * 24 * 60 * 60 * 1000;
  return getAllModels()
    .filter(m => new Date(m.addedDate).getTime() > cutoff)
    .sort((a, b) => b.addedDate.localeCompare(a.addedDate));
}

/** Models that fit in a given VRAM amount */
export function getCompatibleModels(vramGb: number): Model[] {
  return getAllModels().filter(m => m.vramQ4 <= vramGb * 0.92);
}

/** All unique families */
export function getFamilies(): string[] {
  return Array.from(new Set(MODELS.map(m => m.family)));
}

/** All unique tags */
export function getAllTags(): string[] {
  return Array.from(new Set(MODELS.flatMap(m => m.tags))).sort();
}
